# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
dist: trusty
sudo: required
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'

## for sf
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# https://thecoatlessprofessor.com/programming/selecting-an-alternative-compiler-for-r-package-testing-on-travis-ci/
# Install new packages via ubuntu's apt-get manager
# View available compilers in the ubuntu-toolchain-r ppa at:
# https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang
