# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_make_colours <- function(lst_params, params, data, lst_defaults, col_index, palette_type, alpha, colour_name, include_legend, legend_digits = 2L, colour_format = "hex") {
    .Call(`_spatialwidget_rcpp_make_colours`, lst_params, params, data, lst_defaults, col_index, palette_type, alpha, colour_name, include_legend, legend_digits, colour_format)
}

rcpp_resolve_colour <- function(lst_params, params, data, lst_defaults, colour_name, opacity_name, lst_legend, include_legend, colour_format = "hex") {
    .Call(`_spatialwidget_rcpp_resolve_colour`, lst_params, params, data, lst_defaults, colour_name, opacity_name, lst_legend, include_legend, colour_format)
}

rcpp_construct_data <- function(param_names, params, data_names, lst_defaults, data, data_rows) {
    .Call(`_spatialwidget_rcpp_construct_data`, param_names, params, data_names, lst_defaults, data, data_rows)
}

rcpp_geojson <- function(sf, geometry) {
    .Call(`_spatialwidget_rcpp_geojson`, sf, geometry)
}

rcpp_geojson_sf <- function(sf, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_sf`, sf, geometries)
}

rcpp_geojson_df <- function(df, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_df`, df, geometries)
}

rcpp_geojson_dfz <- function(df, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_dfz`, df, geometries)
}

rcpp_construct_legend_list <- function(lst_params, params, param_names, legend_types) {
    .Call(`_spatialwidget_rcpp_construct_legend_list`, lst_params, params, param_names, legend_types)
}

rcpp_set_legend_option <- function(opts, option, value, colour_name) {
    .Call(`_spatialwidget_rcpp_set_legend_option`, opts, option, value, colour_name)
}

rcpp_to_geojson_mesh <- function(mesh, vertices) {
    .Call(`_spatialwidget_rcpp_to_geojson_mesh`, mesh, vertices)
}

rcpp_resolve_palette <- function(lst_params, params) {
    .Call(`_spatialwidget_rcpp_resolve_palette`, lst_params, params)
}

rcpp_colour_str_with_palette <- function(palette, fill_colour_vec, alpha, na_colour, include_alpha, colour_name) {
    .Call(`_spatialwidget_rcpp_colour_str_with_palette`, palette, fill_colour_vec, alpha, na_colour, include_alpha, colour_name)
}

rcpp_colour_num_with_palette <- function(palette, fill_colour_vec, alpha, na_colour, include_alpha, colour_name, legend_digits = 2L) {
    .Call(`_spatialwidget_rcpp_colour_num_with_palette`, palette, fill_colour_vec, alpha, na_colour, include_alpha, colour_name, legend_digits)
}

rcpp_construct_params <- function(data, params) {
    .Call(`_spatialwidget_rcpp_construct_params`, data, params)
}

rcpp_params_to_data <- function(data, params, lst_defaults, layer_legend, data_rows, parameter_exclusions, factors_as_string) {
    .Call(`_spatialwidget_rcpp_params_to_data`, data, params, lst_defaults, layer_legend, data_rows, parameter_exclusions, factors_as_string)
}

rcpp_fill_vector <- function(lst_defaults, param_name, value, n_rows) {
    .Call(`_spatialwidget_rcpp_fill_vector`, lst_defaults, param_name, value, n_rows)
}

rcpp_where_is <- function(to_find, sv) {
    .Call(`_spatialwidget_rcpp_where_is`, to_find, sv)
}

rcpp_remove_list_elements <- function(lst, to_remove) {
    .Call(`_spatialwidget_rcpp_remove_list_elements`, lst, to_remove)
}

is_hex <- function(hex_str) {
    .Call(`_spatialwidget_is_hex`, hex_str)
}

rcpp_widget_line <- function(data, params, geometry_columns, jsonify_legend, digits) {
    .Call(`_spatialwidget_rcpp_widget_line`, data, params, geometry_columns, jsonify_legend, digits)
}

rcpp_widget_point <- function(data, params, geometry_columns, jsonify_legend, digits) {
    .Call(`_spatialwidget_rcpp_widget_point`, data, params, geometry_columns, jsonify_legend, digits)
}

rcpp_widget_point_df <- function(data, params, geometries, jsonify_legend, digits) {
    .Call(`_spatialwidget_rcpp_widget_point_df`, data, params, geometries, jsonify_legend, digits)
}

rcpp_widget_point_df_columnar <- function(data, params, geometry_columns, jsonify_legend, digits) {
    .Call(`_spatialwidget_rcpp_widget_point_df_columnar`, data, params, geometry_columns, jsonify_legend, digits)
}

rcpp_widget_polygon <- function(data, params, geometry_columns, jsonify_legend, digits) {
    .Call(`_spatialwidget_rcpp_widget_polygon`, data, params, geometry_columns, jsonify_legend, digits)
}

