# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

line_example_geojson <- function(data, data_types, params, geometry_columns) {
    .Call(`_spatialwidget_line_example_geojson`, data, data_types, params, geometry_columns)
}

spatialwidget_geojson <- function(data, data_types, params, defaults, colours, legend, geometry) {
    .Call(`_spatialwidget_spatialwidget_geojson`, data, data_types, params, defaults, colours, legend, geometry)
}

rcpp_fill_single_vector <- function(lst_defaults, param_name, value, n_rows) {
    .Call(`_spatialwidget_rcpp_fill_single_vector`, lst_defaults, param_name, value, n_rows)
}

rcpp_find_character_index_in_vector <- function(sv, to_find) {
    .Call(`_spatialwidget_rcpp_find_character_index_in_vector`, sv, to_find)
}

