# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_construct_data <- function(param_names, params, data_names, lst_defaults, data, data_rows) {
    .Call(`_spatialwidget_rcpp_construct_data`, param_names, params, data_names, lst_defaults, data, data_rows)
}

rcpp_geojson <- function(sf, geometry) {
    .Call(`_spatialwidget_rcpp_geojson`, sf, geometry)
}

rcpp_geojson_sf <- function(sf, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_sf`, sf, geometries)
}

rcpp_geojson_df <- function(df, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_df`, df, geometries)
}

rcpp_geojson_dfz <- function(df, geometries) {
    .Call(`_spatialwidget_rcpp_geojson_dfz`, df, geometries)
}

rcpp_sf_to_geojson_downcast <- function(sf, geometry_column) {
    .Call(`_spatialwidget_rcpp_sf_to_geojson_downcast`, sf, geometry_column)
}

rcpp_sf_to_geojson_multi_column_downcast <- function(sf, geometries) {
    .Call(`_spatialwidget_rcpp_sf_to_geojson_multi_column_downcast`, sf, geometries)
}

rcpp_resolve_palette <- function(lst_params, params) {
    .Call(`_spatialwidget_rcpp_resolve_palette`, lst_params, params)
}

rcpp_colour_str_with_palette <- function(palette, fill_colour_vec, alpha, na_colour, include_alpha) {
    .Call(`_spatialwidget_rcpp_colour_str_with_palette`, palette, fill_colour_vec, alpha, na_colour, include_alpha)
}

rcpp_colour_num_with_palette <- function(palette, fill_colour_vec, alpha, na_colour, include_alpha) {
    .Call(`_spatialwidget_rcpp_colour_num_with_palette`, palette, fill_colour_vec, alpha, na_colour, include_alpha)
}

rcpp_fill_vector <- function(lst_defaults, param_name, value, n_rows) {
    .Call(`_spatialwidget_rcpp_fill_vector`, lst_defaults, param_name, value, n_rows)
}

rcpp_where_is <- function(to_find, sv) {
    .Call(`_spatialwidget_rcpp_where_is`, to_find, sv)
}

rcpp_remove_list_elements <- function(lst, to_remove) {
    .Call(`_spatialwidget_rcpp_remove_list_elements`, lst, to_remove)
}

is_hex <- function(hex_str) {
    .Call(`_spatialwidget_is_hex`, hex_str)
}

rcpp_widget_line <- function(data, data_types, params, geometry_columns, jsonify_legend) {
    .Call(`_spatialwidget_rcpp_widget_line`, data, data_types, params, geometry_columns, jsonify_legend)
}

rcpp_widget_point <- function(data, data_types, params, geometry_columns, jsonify_legend) {
    .Call(`_spatialwidget_rcpp_widget_point`, data, data_types, params, geometry_columns, jsonify_legend)
}

rcpp_widget_point_df <- function(data, data_types, params, geometries, jsonify_legend) {
    .Call(`_spatialwidget_rcpp_widget_point_df`, data, data_types, params, geometries, jsonify_legend)
}

rcpp_widget_polygon <- function(data, data_types, params, geometry_columns, jsonify_legend) {
    .Call(`_spatialwidget_rcpp_widget_polygon`, data, data_types, params, geometry_columns, jsonify_legend)
}

